language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer selfupdate --quiet
  - composer install -n
  - mkdir -p build/logs\

script:
  - composer test

after_script:
  - php vendor/bin/coveralls -v
